CREATE DATABASE Biblioteca;



CREATE TABLE Autor(
IdAutor SMALLINT IDENTITY,
NomeAutor VARCHAR(50) NOT NULL,
SobreNomeAutor VARCHAR(60) NOT NULL,
CONSTRAINT pk_id_autor PRIMARY KEY(IdAutor)
);

CREATE TABLE Editora (
IdEditora SMALLINT PRIMARY KEY IDENTITTY,
NomeEditora VARCHAR(50) NOT NULL
);